name: Scan IDFM Trafic H24

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  refresh-trafic:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4 # Passage à la v4 pour éviter l'avertissement jaune de Node.js

      - name: Installer Python
        uses: actions/setup-python@v5 # Passage à la v5
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: pip install requests

      - name: Lancer le script de scan
        run: python update_trafic.py

      - name: Sauvegarder les changements sur GitHub
        run: |
          git config --global user.name 'Robot Trafic'
          git config --global user.email 'robot@trafic.idf'
          git add trafic.json historique.json
          # La magie est ici : on intègre le jeton secret GITHUB_TOKEN directement dans l'URL du push pour forcer le passage
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 MAJ Trafic & Historique en continu" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main)
