name: Update RATP Traffic Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    # On force la déclaration des droits ici au cas où l'interface GitHub bugue
    permissions:
      contents: write
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Lancement du script de récupération
      run: node fetch-trafic.js

    - name: Sauvegarde et Commit du fichier JSON sur GitHub
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add trafic.json
        git commit -m "Mise à jour auto du trafic" || exit 0
        git push origin main
